data/phi0917/phi001/phi0917.phi001.perseus-lat1.xml

All corrections checked against Weise's print edition.

Fixed miscellaneous typos in Lucan BC 1

---

data/phi0690/phi003/phi0690.phi003.perseus-lat1.xml
data/phi0917/phi001/phi0917.phi001.perseus-lat1.xml

All checked against Weise's text

Fixed typos in Lucan text

---

data/phi1348/abo012/phi1348.abo012.perseus-lat1.xml

- gap have been checked against the following pages :
- https://archive.org/stream/csuetoniitranqu00ihmgoog#page/n141/mode/2up
- https://archive.org/stream/csuetoniitranqu00ihmgoog#page/n149/mode/2up
- https://archive.org/stream/csuetoniitranqu00ihmgoog#page/n185/mode/2up
- TEI Namespace has been fixed
- Changes have been reformated through regexp
- Revision \d.\d+ (\d{4})\W(\d{2})\W(\d{2}) \d{2}\W\d{2}\W\d{2} (\w+) (.*)$
- Abbreviation fixed
- Epidoc compliancy

Fixed and moved to CTS

---

data/phi0474/phi002/phi0474.phi002.perseus-lat1.xml
data/phi0474/phi013/phi0474.phi013.perseus-lat1.xml
data/phi0474/phi024/phi0474.phi024.perseus-lat1.xml

Fixes Cicero nearly CTSized for Capitains compliancy.

Phi0474 fixes

---

data/phi0550/phi001/__cts__.xml
data/phi0550/phi001/phi0550.phi001.perseus-eng1.xml
data/phi0550/phi001/phi0550.phi001.perseus-lat1.xml

Phi0550.phi001

---

data/stoa0255/stoa010/stoa0255.stoa010.perseus-lat2.xml

(0255.010.lat2) Adjusting CS

---

data/phi0472/phi001/phi0472.phi001.perseus-eng3.xml
data/phi1038/phi001/phi1038.phi001.perseus-lat1.xml
data/phi1242/phi001/phi1242.phi001.perseus-lat1.xml
data/stoa0162/stoa004/stoa0162.stoa004.perseus-lat2.xml
data/stoa0276/stoa002/stoa0276.stoa002.opp-lat1.xml

- phi0472.phi001.perseus-eng3
- phi1038.phi001.perseus-lat1
- phi1242.phi001.perseus-lat1
- stoa0162.stoa004.perseus-lat2

(Various) Fixed duplicates

---

data/phi0474/phi008/phi0474.phi008.perseus-eng1.xml
data/phi0474/phi008/phi0474.phi008.perseus-lat1.xml

Changes to be committed:
modified:   data/phi0474/phi008/phi0474.phi008.perseus-eng1.xml
modified:   data/phi0474/phi008/phi0474.phi008.perseus-lat1.xml

 On branch phi0474.phi008

---

data/phi0474/phi001/phi0474.phi001.perseus-eng2.xml
data/phi0474/phi002/phi0474.phi002.perseus-eng2.xml
data/phi0474/phi003/phi0474.phi003.perseus-eng2.xml
data/phi0474/phi003/phi0474.phi003.perseus-lat2.xml
data/phi0474/phi004/phi0474.phi004.perseus-eng2.xml
data/phi0474/phi004/phi0474.phi004.perseus-lat2.xml
data/phi0474/phi005/phi0474.phi005.perseus-eng2.xml
data/phi0474/phi005/phi0474.phi005.perseus-lat2.xml
data/phi0474/phi006/phi0474.phi006.perseus-eng2.xml
data/phi0474/phi006/phi0474.phi006.perseus-lat2.xml

Phi0474.phi00X

---

.gitignore
.travis.yml

Reverts PerseusDL/canonical-latinLit#208

Revert "Travis"

---

data/phi0959/phi006/phi0959.phi006.perseus-lat2.xml

addressing some issues raised in #211

typo fixes

---

data/stoa0045/stoa002/stoa0045.stoa002.perseus-lat2.xml

Fix in MyCapytain now allows this text to pass

Corrected stoa0045.stoa002

---

data/phi0119/phi016/phi0119.phi016.perseus-lat1.xml

(missing-files) re-added earlier version of work

---

data/phi0690/phi003/__cts__.xml
data/phi0690/phi003/phi0690.phi003.perseus-lat2.xml

(typo fixes) phi0690.phi003.perseus-lat2

---

data/phi0119/phi012/phi0119.phi012.perseus-eng2.xml

This is the reason that the text was causing the build to fail

Added a missing value to an n attribute

---

data/stoa0045/stoa002/__cts__.xml

Hi @lcerrato we're starting to go through some of the canonical texts for use with Alpheios. Will submit some PRs as we go. Let me know if you'd prefer that we just work in a fork and submit them in batches. Thanks :-)

use the work/edition title not the host title?

---

data/phi0448/phi001/__cts__.xml

phi0448.phi001 Update __cts__.xml

---

data/phi0448/phi001/phi0448.phi001.perseus-eng2.xml
data/phi0448/phi001/phi0448.phi001.perseus-lat2.xml
data/phi1254/phi001/phi1254.phi001.perseus-lat2.xml

phi0448.phi001.perseus-eng/lat2.xml bad chapter/sections; phi1254.phi001.perseus-lat2.xml first pass errors as found in report #304

(Typo fixes) various

---

data/phi0448/phi001/phi0448.phi001.perseus-lat2.xml

(phi0448.phi001.perseus-lat2.xml) typos

---

data/phi0474/phi056/phi0474.phi056.perseus-lat1.xml

(typos-errors) phi0474.phi056.perseus-lat1.xml

---

data/phi0448/phi001/phi0448.phi001.perseus-lat2.xml

phi0448.phi001.perseus-lat2.xml

---

data/phi0474/phi023/__cts__.xml
data/phi0474/phi023/phi0474.phi023.perseus-lat1.xml
data/phi0474/phi023/phi0474.phi023.perseus-lat2.xml

(phi0474.phi023.perseus-lat1.xml) EpiDoc and CTS conversion

---

data/phi0474/phi025/__cts__.xml
data/phi0474/phi025/phi0474.phi025.perseus-lat1.xml
data/phi0474/phi025/phi0474.phi025.perseus-lat2.xml

(phi0474.phi025.perseus-lat1.xml) EpiDoc and CTS conversion

---

data/phi0474/phi026/__cts__.xml
data/phi0474/phi026/phi0474.phi026.perseus-lat1.xml
data/phi0474/phi026/phi0474.phi026.perseus-lat2.xml

(phi0474.phi026.perseus-lat1.xml) EpiDoc and CTS conversion

---

data/phi0474/phi028/__cts__.xml
data/phi0474/phi028/phi0474.phi028.perseus-lat1.xml
data/phi0474/phi028/phi0474.phi028.perseus-lat2.xml

(phi0474.phi028.perseus-lat1.xml) EpiDoc and CTS conversion

---

data/phi0474/phi029/__cts__.xml
data/phi0474/phi029/phi0474.phi029.perseus-lat1.xml
data/phi0474/phi029/phi0474.phi029.perseus-lat2.xml

 (phi0474.phi029.perseus-lat1.xml) EpiDoc and CTS conversion

---

data/phi0474/phi030/__cts__.xml
data/phi0474/phi030/phi0474.phi030.perseus-lat1.xml
data/phi0474/phi030/phi0474.phi030.perseus-lat2.xml

(phi0474.phi030.perseus-lat1.xml) EpiDoc and CTS conversion

---

data/phi0474/phi032/__cts__.xml
data/phi0474/phi032/phi0474.phi032.perseus-lat1.xml
data/phi0474/phi032/phi0474.phi032.perseus-lat2.xml

(phi0474.phi032.perseus-lat1.xml) EpiDoc and CTS conversion

---

data/phi0472/phi001/__cts__.xml

phi0472.phi001_cts.xml

---

data/phi0631/phi002/phi0631.phi002.perseus-lat3.xml

Changed _Iugurthain_ to _Iugurtham_.

(phi0631.phi002.perseus-lat3_edit_sjh) corrected typo #406.

---

data/phi0836/__cts__.xml
data/phi0836/phi002/__cts__.xml
data/phi0836/phi002/phi0836.phi002.perseus-eng2.xml
data/phi0836/phi002/phi0836.phi002.perseus-lat4.xml
data/phi0836/phi002/phi0836.phi002.perseus-lat5.xml
data/phi0836/phi002/phi0836.phi002.perseus-lat6.xml

Updated the cts.xml
Took first pass at updating and standardizing the headers.
Thanks for any and all feedback @lcerrato

phi0836.phi002

---

data/phi1294/phi002/__cts__.xml
data/phi1294/phi002/phi1294.phi002.perseus-lat2.xml

First attempt at revisions re #408 
Updated CTS metadata
First effort to update TEI header.

phi1294.phi002.perseus-lat2.xml

---

data/phi1035/__cts__.xml
data/phi1035/phi001/__cts__.xml
data/phi1035/phi001/phi1035.phi001.perseus-lat2.xml

Updated cts_.xml files
Updated header to current standards.

phi1035.phi001

---

data/phi0428/phi001/phi0428.phi001.perseus-lat1.xml
data/phi0448/phi002/phi0448.phi002.perseus-eng2.xml
data/phi0448/phi002/phi0448.phi002.perseus-lat3.xml
data/stoa0040/stoa011/stoa0040.stoa011.perseus-lat1.xml
data/stoa0054/stoa006/stoa0054.stoa006.perseus-eng1.xml
data/stoa0054/stoa006/stoa0054.stoa006.perseus-lat1.xml
data/stoa0058/stoa001/stoa0058.stoa001.perseus-eng1.xml
data/stoa0058/stoa003/stoa0058.stoa003.perseus-eng1.xml
data/stoa0058/stoa006/stoa0058.stoa006.perseus-eng1.xml
data/stoa0058/stoa023/stoa0058.stoa023.perseus-eng1.xml
data/stoa0058/stoa028/stoa0058.stoa028.perseus-eng1.xml

A few of the files have an extra titleStmt tag, this pull request would remove the extra tag.

Fix extra titleStmt tag in files.

---

data/phi1020/__cts__.xml
data/phi1020/phi001/__cts__.xml
data/phi1020/phi001/phi1020.phi001.perseus-lat2.xml
data/phi1020/phi002/__cts__.xml
data/phi1020/phi002/phi1020.phi002.perseus-lat2.xml
data/phi1020/phi003/__cts__.xml
data/phi1020/phi003/phi1020.phi003.perseus-lat2.xml

Updated CTS files and headers per #426.

phi1020.phi001-phi1020.phi003_cts_and_xml

---

data/phi0972/phi001f/phi0972.phi001f.perseus-eng1.xml

(phi0972.phi001f.perseus-eng1.xml ) add head ending tags

---

data/phi0893/phi001/__cts__.xml
data/phi0893/phi001/phi0893.phi001.perseus-eng2.xml
data/phi0893/phi001/phi0893.phi001.perseus-lat2.xml
data/phi0893/phi002/__cts__.xml
data/phi0893/phi002/phi0893.phi002.perseus-lat2.xml
data/phi0893/phi003/__cts__.xml
data/phi0893/phi003/phi0893.phi003.perseus-lat2.xml
data/phi0893/phi004/__cts__.xml
data/phi0893/phi004/phi0893.phi004.perseus-eng2.xml
data/phi0893/phi004/phi0893.phi004.perseus-lat2.xml
data/phi0893/phi005/__cts__.xml
data/phi0893/phi005/phi0893.phi005.perseus-lat2.xml
data/phi0893/phi006/__cts__.xml
data/phi0893/phi006/phi0893.phi006.perseus-eng2.xml
data/phi0893/phi006/phi0893.phi006.perseus-lat2.xml

Updated all Horace headers and files per issue #437

(phi0893)-_cts.xml and header fixes

---

data/stoa0023/__cts__.xml
data/stoa0023/stoa001/__cts__.xml
data/stoa0023/stoa001/stoa0023.stoa001.perseus-eng2.xml
data/stoa0023/stoa001/stoa0023.stoa001.perseus-lat2.xml

Updated cts file, headers, and bibliographic info.

(stoa0023.stoa001).perseus-eng2/lat2

---

data/phi0959/phi005/__cts__.xml
data/phi0959/phi005/phi0959.phi005.perseus-eng2.xml
data/phi0959/phi005/phi0959.phi005.perseus-lat2.xml
data/phi0959/phi006/__cts__.xml
data/phi0959/phi006/phi0959.phi006.perseus-eng3.xml
data/phi0959/phi006/phi0959.phi006.perseus-eng4.xml
data/phi0959/phi006/phi0959.phi006.perseus-lat2.xml
data/phi0959/phi007/__cts__.xml
data/phi0959/phi007/phi0959.phi007.perseus-lat2.xml
data/phi0959/phi008/__cts__.xml
data/phi0959/phi008/phi0959.phi008.perseus-lat2.xml
data/phi0959/phi009/__cts__.xml
data/phi0959/phi009/phi0959.phi009.perseus-lat2.xml
data/phi0959/phi010/__cts__.xml
data/phi0959/phi010/phi0959.phi010.perseus-lat2.xml

Updated cts descriptions
Updated XML headers
Added in page level links.

(phi0959.phi005)_phi0959.phi010

---

.travis.yml
data/phi0474/__cts__.xml
data/phi0474/phi001/__cts__.xml
data/phi0474/phi001/phi0474.phi001.perseus-eng2.xml
data/phi0474/phi001/phi0474.phi001.perseus-lat2.xml

First attempt at changes re #448 
Changed the cts work title to the Latin title.
Updated both the title and edition descriptions to current standards.
Updated headers and bibliographic info.
Changed M. Tullius Cicero per earlier conversation on author names, but may have misinterpreted.

(phi0474.phi001).perseus-lat2_perseus-eng2

---

data/phi0474/phi001/phi0474.phi001.perseus-eng2.xml
data/phi0474/phi001/phi0474.phi001.perseus-lat2.xml
data/phi0474/phi002/__cts__.xml
data/phi0474/phi002/phi0474.phi002.perseus-eng2.xml
data/phi0474/phi002/phi0474.phi002.perseus-lat2.xml

Continued updating Cicero
Fixed two mistakes found in last pull request (had lang "alt" not lang "lat"

(phi0474)phi474_001/2

---

data/phi0969/phi001/__cts__.xml
data/phi0969/phi001/phi0969.phi001.perseus-lat2.xml
data/phi0972/phi001/__cts__.xml
data/phi0972/phi001/phi0972.phi001.perseus-lat2.xml
data/phi0975/phi001/__cts__.xml
data/phi0975/phi001/phi0975.phi001.perseus-eng1.xml
data/phi0975/phi001/phi0975.phi001.perseus-lat2.xml

Updated cts_.xml files and minor changes to headers and bibliographic descriptions.

(phi0969_phi0975)

---

data/stoa0275/stoa001/stoa0275.stoa001.opp-lat1.xml
data/stoa0275/stoa002/__cts__.xml
data/stoa0275/stoa002/stoa0275.stoa002.opp-lat1.xml
data/stoa0275/stoa003/stoa0275.stoa003.opp-lat1.xml
data/stoa0275/stoa009/stoa0275.stoa009.perseus-lat2.xml
data/stoa0275/stoa011/__cts__.xml
data/stoa0275/stoa011/stoa0275.stoa011.opp-lat1.xml
data/stoa0275/stoa012/__cts__.xml
data/stoa0275/stoa012/stoa0275.stoa012.opp-lat1.xml
data/stoa0275/stoa013/__cts__.xml
data/stoa0275/stoa013/stoa0275.stoa013.opp-lat1.xml
data/stoa0275/stoa014/__cts__.xml
data/stoa0275/stoa014/stoa0275.stoa014.opp-lat1.xml

Continuing work on Tertullian, and some minor changes to earlier files.

stoa0275.stoa011_stoa0275.stoa014

---

data/stoa0275/stoa015/__cts__.xml
data/stoa0275/stoa015/stoa0275.stoa015.opp-lat1.xml
data/stoa0275/stoa016/__cts__.xml
data/stoa0275/stoa016/stoa0275.stoa016.opp-lat1.xml
data/stoa0275/stoa017/__cts__.xml
data/stoa0275/stoa017/stoa0275.stoa017.opp-lat1.xml
data/stoa0275/stoa018/__cts__.xml
data/stoa0275/stoa018/stoa0275.stoa018.opp-lat1.xml
data/stoa0275/stoa019/__cts__.xml
data/stoa0275/stoa019/stoa0275.stoa019.opp-lat1.xml
data/stoa0275/stoa020/__cts__.xml
data/stoa0275/stoa020/stoa0275.stoa020.opp-lat1.xml
data/stoa0275/stoa021/__cts__.xml
data/stoa0275/stoa021/stoa0275.stoa021.opp-lat1.xml
data/stoa0275/stoa022/__cts__.xml
data/stoa0275/stoa022/stoa0275.stoa022.opp-lat1.xml
data/stoa0275/stoa023/__cts__.xml
data/stoa0275/stoa023/stoa0275.stoa023.opp-lat1.xml
data/stoa0275/stoa024/__cts__.xml
data/stoa0275/stoa024/stoa0275.stoa024.opp-lat1.xml
data/stoa0275/stoa025/__cts__.xml
data/stoa0275/stoa025/stoa0275.stoa025.opp-lat1.xml
data/stoa0275/stoa026/__cts__.xml
data/stoa0275/stoa026/stoa0275.stoa026.opp-lat1.xml
data/stoa0275/stoa028/__cts__.xml
data/stoa0275/stoa028/stoa0275.stoa028.opp-lat1.xml
data/stoa0275/stoa029/__cts__.xml
data/stoa0275/stoa029/stoa0275.stoa029.opp-lat1.xml
data/stoa0275/stoa030/__cts__.xml
data/stoa0275/stoa030/stoa0275.stoa030.opp-lat1.xml

Some continuing work on Tertullian files.

stoa0275.017_stoa0275.stoa020

---

data/stoa0276/stoa002/__cts__.xml
data/stoa0276/stoa002/stoa0276.stoa002.opp-lat1.xml

Updated cts and bibliographic metadata.

(stoa0276).stoa0276.stoa002

---

data/phi0474/phi002/phi0474.phi002.perseus-lat2.xml
data/phi0474/phi003/phi0474.phi003.perseus-lat2.xml
data/phi0474/phi004/phi0474.phi004.perseus-lat2.xml
data/phi0474/phi005/phi0474.phi005.perseus-lat2.xml
data/phi0474/phi006/__cts__.xml
data/phi0474/phi006/phi0474.phi006.perseus-eng2.xml
data/phi0474/phi006/phi0474.phi006.perseus-lat2.xml
data/phi0474/phi007/__cts__.xml
data/phi0474/phi007/phi0474.phi007.perseus-eng2.xml
data/phi0474/phi007/phi0474.phi007.perseus-lat2.xml
data/phi0474/phi008/__cts__.xml
data/phi0474/phi008/phi0474.phi008.perseus-eng2.xml
data/phi0474/phi008/phi0474.phi008.perseus-lat2.xml
data/phi0474/phi009/__cts__.xml
data/phi0474/phi009/phi0474.phi009.perseus-eng2.xml
data/phi0474/phi009/phi0474.phi009.perseus-lat2.xml
data/phi0474/phi010/__cts__.xml
data/phi0474/phi010/phi0474.phi010.perseus-eng2.xml
data/phi0474/phi010/phi0474.phi010.perseus-lat2.xml
data/phi0474/phi011/__cts__.xml
data/phi0474/phi011/phi0474.phi011.perseus-eng2.xml
data/phi0474/phi011/phi0474.phi011.perseus-lat2.xml

Continuing work on Cicero
Minor edits to previous files.

(phi0474.phi006_phi0474.phi011)

---

data/phi1254/__cts__.xml
data/phi1254/phi001/__cts__.xml
data/phi1254/phi001/phi1254.phi001.perseus-eng1.xml
data/phi1254/phi001/phi1254.phi001.perseus-lat2.xml
data/phi1276/phi001/__cts__.xml
data/phi1276/phi001/phi1276.phi001.perseus-lat2.xml

Updated all cts_.xml files and headers
Updated bibliographic descriptions.

(phi1254)(phi1276)

---

data/phi1002/phi001/__cts__.xml
data/phi1002/phi001/phi1002.phi001.perseus-eng2.xml
data/phi1002/phi001/phi1002.phi001.perseus-lat2.xml

Added in edition titles to the cts_.xml
Did not add an English translation title as one was not used in this Loeb edition.

(phi1002)-all files

---

data/phi0620/phi001/__cts__.xml
data/phi0620/phi001/phi0620.phi001.perseus-lat3.xml
data/stoa0238/stoa001/__cts__.xml
data/stoa0238/stoa001/stoa0238.stoa001.perseus-lat2.xml
data/stoa0238/stoa002/__cts__.xml
data/stoa0238/stoa002/stoa0238.stoa002.perseus-lat2.xml
data/stoa0238/stoa003/__cts__.xml
data/stoa0238/stoa003/stoa0238.stoa003.perseus-lat2.xml
data/stoa0238/stoa004/__cts__.xml
data/stoa0238/stoa004/stoa0238.stoa004.perseus-lat2.xml
data/stoa0238/stoa005/__cts__.xml
data/stoa0238/stoa005/stoa0238.stoa005.perseus-lat2.xml
data/stoa0238/stoa006/__cts__.xml
data/stoa0238/stoa006/stoa0238.stoa006.perseus-lat2.xml
data/stoa0238/stoa007/__cts__.xml
data/stoa0238/stoa007/stoa0238.stoa007.perseus-lat2.xml
data/stoa0238/stoa008/__cts__.xml
data/stoa0238/stoa008/stoa0238.stoa008.perseus-lat2.xml
data/stoa0238/stoa009/__cts__.xml
data/stoa0238/stoa009/stoa0238.stoa009.perseus-lat2.xml

Updated Propertius and all of Prudentius files.
Updated cts_.xml and bibliographic descriptions.
Added in page links.

phi0620_stoa0238

---

data/stoa0162/stoa004/__cts__.xml
data/stoa0162/stoa004/stoa0162.stoa004.perseus-lat2.xml

updating cts_.xml and bibliographic information.

(stoa0162)stoa0162.stoa004

---

data/phi1276/phi001/__cts__.xml

phi1276phi001 cts file

---

data/phi2331/phi001/phi2331.phi001.perseus-lat2.xml
data/phi2331/phi002/__cts__.xml
data/phi2331/phi002/phi2331.phi002.perseus-lat2.xml
data/phi2331/phi003/__cts__.xml
data/phi2331/phi003/phi2331.phi003.perseus-lat2.xml
data/phi2331/phi004/__cts__.xml
data/phi2331/phi004/phi2331.phi004.perseus-lat2.xml
data/phi2331/phi005/__cts__.xml
data/phi2331/phi005/phi2331.phi005.perseus-lat2.xml
data/phi2331/phi006/__cts__.xml
data/phi2331/phi006/phi2331.phi006.perseus-lat2.xml
data/phi2331/phi007/__cts__.xml
data/phi2331/phi007/phi2331.phi007.perseus-lat2.xml
data/phi2331/phi008/__cts__.xml
data/phi2331/phi008/phi2331.phi008.perseus-lat2.xml
data/phi2331/phi009/__cts__.xml
data/phi2331/phi009/phi2331.phi009.perseus-lat2.xml
data/phi2331/phi010/__cts__.xml
data/phi2331/phi010/phi2331.phi010.perseus-lat2.xml
data/phi2331/phi011/__cts__.xml
data/phi2331/phi011/phi2331.phi011.perseus-lat2.xml
data/phi2331/phi012/__cts__.xml
data/phi2331/phi012/phi2331.phi012.perseus-lat2.xml

Made bilbiographic fixes and changes to all works in Volume 1 for the SHA.

(phi2331)_phi2331.phi001_phi2331.phi012

---

data/phi2331/phi022/__cts__.xml
data/phi2331/phi022/phi2331.phi022.perseus-lat2.xml
data/phi2331/phi023/__cts__.xml
data/phi2331/phi023/phi2331.phi023.perseus-lat2.xml
data/phi2331/phi024/__cts__.xml
data/phi2331/phi024/phi2331.phi024.perseus-lat2.xml
data/phi2331/phi025/__cts__.xml
data/phi2331/phi025/phi2331.phi025.perseus-lat2.xml
data/phi2331/phi026/__cts__.xml
data/phi2331/phi026/phi2331.phi026.perseus-lat2.xml
data/phi2331/phi027/__cts__.xml
data/phi2331/phi027/phi2331.phi027.perseus-lat2.xml
data/phi2331/phi028/__cts__.xml
data/phi2331/phi028/phi2331.phi028.perseus-lat2.xml
data/phi2331/phi029/__cts__.xml
data/phi2331/phi029/phi2331.phi029.perseus-lat2.xml
data/phi2331/phi030/__cts__.xml
data/phi2331/phi030/phi2331.phi030.perseus-lat2.xml

(phi2331).phi2331.phi022_phi2331.phi030

---

data/phi2331/phi013/__cts__.xml
data/phi2331/phi013/phi2331.phi013.perseus-lat2.xml
data/phi2331/phi014/__cts__.xml
data/phi2331/phi014/phi2331.phi014.perseus-lat2.xml
data/phi2331/phi015/__cts__.xml
data/phi2331/phi015/phi2331.phi015.perseus-lat2.xml
data/phi2331/phi016/__cts__.xml
data/phi2331/phi016/phi2331.phi016.perseus-lat2.xml
data/phi2331/phi017/__cts__.xml
data/phi2331/phi017/phi2331.phi017.perseus-lat2.xml
data/phi2331/phi018/__cts__.xml
data/phi2331/phi018/phi2331.phi018.perseus-lat2.xml
data/phi2331/phi019/__cts__.xml
data/phi2331/phi019/phi2331.phi019.perseus-lat2.xml
data/phi2331/phi020/__cts__.xml
data/phi2331/phi020/phi2331.phi020.perseus-lat2.xml
data/phi2331/phi021/__cts__.xml
data/phi2331/phi021/phi2331.phi021.perseus-lat2.xml

This is a new branch with only the files that need fixing. @lcerrato if you could check these files quickly that would be great but I will hold off on merging if it is correct until the build problem is ultimately fixed. Thanks!

(phi2331)phi0013_phi0021

---

data/phi0690/phi003/phi0690.phi003.perseus-lat2.xml
data/phi0917/phi001/phi0917.phi001.perseus-lat2.xml

(typo-fixes) various errors

---

data/phi0474/phi055/__cts__.xml
data/phi0474/phi055/phi0474.phi055.perseus-eng1.xml
data/phi0474/phi055/phi0474.phi055.perseus-lat1.xml
data/phi0972/phi001/phi0972.phi001.perseus-lat1.xml
data/phi0972/phi001/phi0972.phi001.perseus-lat2.xml
data/phi0972/phi001p/phi0972.phi001p.perseus-eng1.xml
data/phi0972/phi001p/phi0972.phi001p.perseus-lat1.xml

Updated/Corrected the headers and metadata, added in some page level links, per #163.

(phi0474)(phi0972)

---

data/phi0660/__cts__.xml
data/phi0660/phi001/__cts__.xml
data/phi0660/phi001/phi0660.phi001.perseus-lat2.xml
data/phi0660/phi003/__cts__.xml
data/phi0660/phi003/phi0660.phi003.perseus-eng2.xml
data/phi0660/phi003/phi0660.phi003.perseus-lat2.xml
data/phi0914/phi001/phi0914.phi001.perseus-eng3.xml

Updated headers and bibliographic information for both files. Added in links for English translation after hunting down an online version.

(phi0914).phi0914.phi001

---

data/phi0914/phi001/__cts__.xml

Attempting to update cts_.xml here, was unable to push a branch from my local repository.

phi0914.phi001_cts_.xml

---

data/phi0588/abo001/__cts__.xml
data/phi0588/abo001/phi0588.abo001.perseus-lat2.xml
data/phi0588/abo002/__cts__.xml
data/phi0588/abo002/phi0588.abo002.perseus-lat2.xml
data/phi0588/abo003/__cts__.xml
data/phi0588/abo003/phi0588.abo003.perseus-lat2.xml
data/phi0588/abo004/__cts__.xml
data/phi0588/abo004/phi0588.abo004.perseus-lat2.xml
data/phi0588/abo005/__cts__.xml
data/phi0588/abo005/phi0588.abo005.perseus-lat2.xml
data/phi0588/abo006/__cts__.xml
data/phi0588/abo006/phi0588.abo006.perseus-lat2.xml

phi0588.phi001 and phi0588.phi002
Updated cts_.xml and headers.
Slightly edited bibliographic metadata and then added in page level links.
hi @lcerrato I just wanted to make sure the way I changed these two files was ok before I go through with the rests, its nice to have all the works in one edition for once.

(phi0588)_all_files (eventually)

---

data/stoa0203/stoa001/__cts__.xml
data/stoa0203/stoa001/stoa0203.stoa001.perseus-lat2.xml

Updated cts_xml and the header.

(stoa0203)_stoa001

---

data/phi0588/abo007/__cts__.xml
data/phi0588/abo007/phi0588.abo007.perseus-lat2.xml
data/phi0588/abo008/__cts__.xml
data/phi0588/abo008/phi0588.abo008.perseus-lat2.xml
data/phi0588/abo009/__cts__.xml
data/phi0588/abo009/phi0588.abo009.perseus-lat2.xml
data/phi0588/abo010/__cts__.xml
data/phi0588/abo010/phi0588.abo010.perseus-lat2.xml
data/phi0588/abo011/__cts__.xml
data/phi0588/abo011/phi0588.abo011.perseus-lat2.xml
data/phi0588/abo012/__cts__.xml
data/phi0588/abo012/phi0588.abo012.perseus-lat2.xml

phi0588.phi007_phi0588.phi012

---

data/phi1212/phi001/__cts__.xml
data/phi1212/phi001/phi1212.phi001.perseus-lat1.xml
data/phi1212/phi002/__cts__.xml
data/phi1212/phi002/phi1212.phi002.perseus-eng1.xml
data/phi1212/phi002/phi1212.phi002.perseus-lat1.xml
data/phi1212/phi003/phi1212.phi003.perseus-lat2.xml

Updated cts_.xml and other metadata for these files. Last commit before vacation!
I know this may fail @lcerrato I just had these changes and didn't want to forgot to do the pull request!

(phi1212.phi001_phi003)

---

data/phi0588/abo013/__cts__.xml
data/phi0588/abo013/phi0588.abo013.perseus-lat2.xml
data/phi0588/abo014/__cts__.xml
data/phi0588/abo014/phi0588.abo014.perseus-lat2.xml
data/phi0588/abo015/__cts__.xml
data/phi0588/abo015/phi0588.abo015.perseus-lat2.xml
data/phi0588/abo016/__cts__.xml
data/phi0588/abo016/phi0588.abo016.perseus-lat2.xml
data/phi0588/abo017/__cts__.xml
data/phi0588/abo017/phi0588.abo017.perseus-lat2.xml
data/phi0588/abo018/__cts__.xml
data/phi0588/abo018/phi0588.abo018.perseus-lat2.xml
data/phi0588/abo019/__cts__.xml
data/phi0588/abo019/phi0588.abo019.perseus-lat2.xml
data/phi0588/abo020/__cts__.xml
data/phi0588/abo020/phi0588.abo020.perseus-lat2.xml
data/phi0588/abo021/__cts__.xml
data/phi0588/abo021/phi0588.abo021.perseus-lat2.xml
data/phi0588/abo022/__cts__.xml
data/phi0588/abo022/phi0588.abo022.perseus-lat2.xml
data/phi0588/abo023/__cts__.xml
data/phi0588/abo023/phi0588.abo023.perseus-lat2.xml
data/phi0588/abo024/__cts__.xml
data/phi0588/abo024/phi0588.abo024.perseus-lat2.xml
data/phi0588/abo025/__cts__.xml
data/phi0588/abo025/phi0588.abo025.perseus-lat2.xml

Last batch of Nepos that I fixed a while back but had forgotten to commit.

phi0588_rest_of_files

---

data/phi0119/phi001/phi0119.phi001.perseus-eng2.xml
data/phi0119/phi002/phi0119.phi002.perseus-eng2.xml
data/phi0119/phi003/phi0119.phi003.perseus-eng2.xml
data/phi0119/phi004/phi0119.phi004.perseus-eng2.xml
data/phi0119/phi005/phi0119.phi005.perseus-eng2.xml
data/phi0119/phi006/phi0119.phi006.perseus-eng2.xml
data/phi0119/phi007/phi0119.phi007.perseus-eng2.xml
data/phi0119/phi008/__cts__.xml
data/phi0119/phi008/phi0119.phi008.perseus-eng2.xml
data/phi0119/phi009/phi0119.phi009.perseus-eng2.xml
data/phi0119/phi010/phi0119.phi010.perseus-eng2.xml

I've edited the first ten English translations.
Updated title language to mul
Changed author name to Plautus as that is what is used in the printed book Updated bibliographic metadata to include volume number and page level link.

(phi0119)_001_to_010--English translations

---

data/phi0119/phi001/phi0119.phi001.perseus-lat2.xml
data/phi0119/phi002/phi0119.phi002.perseus-lat2.xml
data/phi0119/phi003/phi0119.phi003.perseus-lat2.xml
data/phi0119/phi004/phi0119.phi004.perseus-lat2.xml
data/phi0119/phi005/phi0119.phi005.perseus-lat2.xml
data/phi0119/phi006/phi0119.phi006.perseus-lat2.xml
data/phi0119/phi007/phi0119.phi007.perseus-lat2.xml
data/phi0119/phi008/phi0119.phi008.perseus-lat2.xml
data/phi0119/phi009/phi0119.phi009.perseus-lat2.xml
data/phi0119/phi010/phi0119.phi010.perseus-lat2.xml

Updated Latin editions headers, language tagging
Added in volume info and page level links .

(phi0119)001_to_010

---

data/phi0119/phi011/phi0119.phi011.perseus-lat2.xml
data/phi0119/phi012/phi0119.phi012.perseus-lat2.xml
data/phi0119/phi013/phi0119.phi013.perseus-lat2.xml
data/phi0119/phi014/phi0119.phi014.perseus-lat2.xml
data/phi0119/phi015/phi0119.phi015.perseus-lat2.xml
data/phi0119/phi016/phi0119.phi016.perseus-lat2.xml
data/phi0119/phi017/phi0119.phi017.perseus-lat2.xml
data/phi0119/phi018/phi0119.phi018.perseus-lat2.xml
data/phi0119/phi019/phi0119.phi019.perseus-lat2.xml
data/phi0119/phi020/phi0119.phi020.perseus-lat2.xml

Final batch of Suetonius Latin files.

(phi0119)_011_020

---

data/phi0472/phi001/phi0472.phi001.perseus-lat2.xml
data/phi0959/phi006/phi0959.phi006.perseus-lat2.xml
data/phi1020/phi001/phi1020.phi001.perseus-lat2.xml
data/phi1035/phi001/phi1035.phi001.perseus-lat2.xml

fix #538 error report phi0914.phi001-lat2; 
fix #527 phi0472.phi001; 
fix #523 
fix #526 phi1020.phi001-lat2; 
fix #524 phi0959.phi006; 
fix #525 phi1035.phi001-lat2

(typo-fixes) various error reports

---

data/phi0474/phi001/__cts__.xml
data/phi0474/phi002/__cts__.xml
data/phi0474/phi003/__cts__.xml
data/phi0474/phi004/__cts__.xml
data/phi0474/phi005/__cts__.xml
data/phi0474/phi006/__cts__.xml
data/phi0474/phi007/__cts__.xml
data/phi0474/phi008/__cts__.xml
data/phi0474/phi009/__cts__.xml
data/phi0474/phi010/__cts__.xml
data/phi0474/phi011/__cts__.xml
data/phi0474/phi011/phi0474.phi011.perseus-lat2.xml
data/phi0474/phi012/__cts__.xml
data/phi0474/phi012/phi0474.phi012.perseus-lat2.xml
data/phi0474/phi013/__cts__.xml
data/phi0474/phi013/phi0474.phi013.perseus-lat2.xml
data/phi0474/phi014/__cts__.xml
data/phi0474/phi014/phi0474.phi014.perseus-lat2.xml
data/phi0474/phi015/__cts__.xml
data/phi0474/phi015/phi0474.phi015.perseus-lat2.xml
data/phi0474/phi016/__cts__.xml
data/phi0474/phi016/phi0474.phi016.perseus-lat2.xml
data/phi0474/phi017/__cts__.xml
data/phi0474/phi017/phi0474.phi017.perseus-lat2.xml
data/phi0474/phi018/__cts__.xml
data/phi0474/phi018/phi0474.phi018.perseus-lat2.xml
data/phi0474/phi019/__cts__.xml

Updated cts_.xml files and the Latin editions.

phi0474_012_019

---

data/phi0474/phi018/phi0474.phi018.perseus-lat2.xml
data/phi0474/phi019/__cts__.xml
data/phi0474/phi019/phi0474.phi019.perseus-eng2.xml
data/phi0474/phi019/phi0474.phi019.perseus-lat2.xml
data/phi0474/phi020/__cts__.xml
data/phi0474/phi020/phi0474.phi020.perseus-lat2.xml
data/phi0474/phi021/__cts__.xml
data/phi0474/phi021/phi0474.phi021.perseus-lat2.xml
data/phi0474/phi022/__cts__.xml
data/phi0474/phi022/phi0474.phi022.perseus-lat2.xml
data/phi0474/phi023/phi0474.phi023.perseus-lat2.xml
data/phi0474/phi024/__cts__.xml
data/phi0474/phi024/phi0474.phi024.perseus-lat2.xml
data/phi0474/phi025/__cts__.xml
data/phi0474/phi025/phi0474.phi025.perseus-lat2.xml
data/phi0474/phi026/__cts__.xml
data/phi0474/phi026/phi0474.phi026.perseus-lat2.xml

Updating cts_.xml files and Latin translations with some metadata changes.

phi0474.018_026

---

data/phi0474/phi027/__cts__.xml
data/phi0474/phi027/phi0474.phi027.perseus-lat2.xml
data/phi0474/phi028/__cts__.xml
data/phi0474/phi028/phi0474.phi028.perseus-lat2.xml
data/phi0474/phi029/__cts__.xml
data/phi0474/phi029/phi0474.phi029.perseus-lat2.xml
data/phi0474/phi030/__cts__.xml
data/phi0474/phi030/phi0474.phi030.perseus-lat2.xml
data/phi0474/phi031/__cts__.xml
data/phi0474/phi031/phi0474.phi031.perseus-lat2.xml
data/phi0474/phi032/__cts__.xml
data/phi0474/phi032/phi0474.phi032.perseus-lat2.xml
data/phi0474/phi033/__cts__.xml
data/phi0474/phi033/phi0474.phi033.perseus-lat2.xml
data/phi0474/phi034/__cts__.xml
data/phi0474/phi034/phi0474.phi034.perseus-lat2.xml
data/phi0474/phi035/__cts__.xml
data/phi0474/phi035/phi0474.phi035.perseus-lat2.xml

Updated cts_.xml files with Latin titles.
Added some language tagging, series info, and page level links to HathiTrust for a few volumes (no Internet Archive file)

phi0474.phi027_phi035

---

data/phi0917/phi001/__cts__.xml
data/phi0917/phi001/phi0917.phi001.perseus-eng2.xml
data/phi0917/phi001/phi0917.phi001.perseus-lat2.xml

Updated cts_.xml metadata, fixed edition to translation Updated bibliographic metadata

(phi0917).phi0917.phi001

---

.github/workflows/ci.yml

https://github.com/PerseusDL/canonical-greekLit/pull/1521

Backport hooktest fix from https://github.com/PerseusDL/canonical-greekLit/pull/1521

---

.github/workflows/ci.yml

Follows https://github.com/PerseusDL/canonical-latinLit/pull/552

Pin create_release Python version

---

data/phi1254/phi001/phi1254.phi001.perseus-lat2.xml

fix #560 and address superfluous info

(typos-errors) phi1254.phi001.perseus-lat2

---

data/phi0448/phi001/phi0448.phi001.perseus-lat2.xml

First time contributor, but @lcerrato has reviewed / merged many PRs from me in the L&S repo.

(phi0448.phi001.perseus-lat2.xml) Fix some typos in Caesar DBG

---

data/phi1276/phi001/phi1276.phi001.perseus-lat2.xml

Corrected transcription errors in Juvenal Satires. Changed Sat. Vii.12 Alcitheon > Alcithoen

(phi1276.phi001.perseus-lat2.xml) Juvenal Satire fixes

---

data/phi0474/phi056/phi0474.phi056.perseus-eng1.xml
data/phi0474/phi057/phi0474.phi057.perseus-eng1.xml

typographical errors

---

data/phi1254/phi001/phi1254.phi001.perseus-eng1.xml

(typos_errors) various fixes

---

data/phi0478/phi003/phi0478.phi003.perseus-lat2.xml

- See https://archive.org/details/epistulaerecogno03ciceuoft/page/80/mode/2up

Fix typo in pphi0478.phi003.perseus-lat2.xml

---

data/stoa0255/stoa004/stoa0255.stoa004.perseus-lat2.xml
data/stoa0255/stoa006/__cts__.xml
data/stoa0255/stoa006/stoa0255.stoa006.perseus-lat2.xml
data/stoa0255/stoa007/__cts__.xml
data/stoa0255/stoa007/stoa0255.stoa007.perseus-lat2.xml
data/stoa0255/stoa008/__cts__.xml
data/stoa0255/stoa008/stoa0255.stoa008.perseus-lat2.xml
data/stoa0255/stoa009/__cts__.xml
data/stoa0255/stoa009/stoa0255.stoa009.perseus-lat2.xml
data/stoa0255/stoa010/__cts__.xml
data/stoa0255/stoa010/stoa0255.stoa010.perseus-lat2.xml
data/stoa0255/stoa011/__cts__.xml
data/stoa0255/stoa011/stoa0255.stoa011.perseus-lat2.xml
data/stoa0255/stoa012/__cts__.xml
data/stoa0255/stoa012/stoa0255.stoa012.perseus-lat2.xml
data/stoa0255/stoa013/__cts__.xml
data/stoa0255/stoa013/stoa0255.stoa013.perseus-lat2.xml
data/stoa0255/stoa014/__cts__.xml
data/stoa0255/stoa014/stoa0255.stoa014.perseus-lat2.xml

Updated cts_xml, headers, and other metadata for Seneca.

stoa0255_all_files

---

data/phi1017/__cts__.xml
data/phi1017/phi001/__cts__.xml
data/phi1017/phi001/phi1017.phi001.perseus-lat2.xml
data/phi1017/phi002/__cts__.xml
data/phi1017/phi002/phi1017.phi002.perseus-lat2.xml
data/phi1017/phi003/__cts__.xml
data/phi1017/phi003/phi1017.phi003.perseus-lat2.xml
data/phi1017/phi004/__cts__.xml
data/phi1017/phi004/phi1017.phi004.perseus-lat2.xml
data/phi1017/phi005/__cts__.xml
data/phi1017/phi005/phi1017.phi005.perseus-lat2.xml
data/phi1017/phi006/__cts__.xml
data/phi1017/phi006/phi1017.phi006.perseus-lat2.xml
data/phi1017/phi007/__cts__.xml
data/phi1017/phi007/phi1017.phi007.perseus-lat2.xml

First half of updated Seneca files
Updated schema, cts_xml and other metadata.

phi1017.phi001_phi.1017.phi007

---

data/phi1017/phi008/__cts__.xml
data/phi1017/phi008/phi1017.phi008.perseus-lat2.xml
data/phi1017/phi009/__cts__.xml
data/phi1017/phi009/phi1017.phi009.perseus-lat2.xml
data/phi1017/phi010/__cts__.xml
data/phi1017/phi010/phi1017.phi010.perseus-lat2.xml
data/phi1017/phi011/__cts__.xml
data/phi1017/phi011/phi1017.phi011.perseus-eng2.xml
data/phi1017/phi011/phi1017.phi011.perseus-lat2.xml
data/phi1017/phi013/__cts__.xml
data/phi1017/phi013/phi1017.phi013.perseus-lat2.xml
data/phi1017/phi014/__cts__.xml
data/phi1017/phi014/phi1017.phi014.perseus-lat2.xml
data/phi1017/phi015/__cts__.xml
data/phi1017/phi015/phi1017.phi015.perseus-lat2.xml

phi1017-second batch of files

---

data/phi0119/phi001/phi0119.phi001.perseus-eng2.xml
data/phi0119/phi001/phi0119.phi001.perseus-lat2.xml
data/phi0119/phi002/phi0119.phi002.perseus-eng2.xml
data/phi0119/phi003/phi0119.phi003.perseus-eng2.xml
data/phi0119/phi004/phi0119.phi004.perseus-eng2.xml
data/phi0119/phi005/phi0119.phi005.perseus-eng2.xml
data/phi0119/phi005/phi0119.phi005.perseus-lat2.xml
data/phi0119/phi006/phi0119.phi006.perseus-eng2.xml
data/phi0119/phi006/phi0119.phi006.perseus-lat2.xml
data/phi0119/phi007/phi0119.phi007.perseus-eng2.xml
data/phi0119/phi007/phi0119.phi007.perseus-lat2.xml
data/phi0119/phi008/phi0119.phi008.perseus-eng2.xml
data/phi0119/phi008/phi0119.phi008.perseus-lat2.xml
data/phi0119/phi009/phi0119.phi009.perseus-eng2.xml
data/phi0119/phi010/phi0119.phi010.perseus-eng2.xml
data/phi0119/phi011/phi0119.phi011.perseus-eng2.xml
data/phi0119/phi012/phi0119.phi012.perseus-eng2.xml
data/phi0119/phi013/phi0119.phi013.perseus-eng2.xml
data/phi0119/phi014/phi0119.phi014.perseus-eng2.xml
data/phi0119/phi015/phi0119.phi015.perseus-eng2.xml
data/phi0119/phi016/phi0119.phi016.perseus-eng2.xml
data/phi0119/phi017/phi0119.phi017.perseus-eng2.xml
data/phi0119/phi018/phi0119.phi018.perseus-eng2.xml
data/phi0119/phi019/phi0119.phi019.perseus-eng2.xml
data/phi0119/phi020/phi0119.phi020.perseus-eng2.xml

continued batch work for viewer optimization

(review_work) various changes to phi0119

---

data/phi0474/phi013/phi0474.phi013.perseus-lat2.xml

The original scan has this as a note: https://archive.org/details/orationesrecogno01ciceuoft/page/n253/mode/2up

Add missing <note> tag in phi0474.phi013.perseus-lat2
