PerseusDL/canonical-latinLit

data/stoa0255/stoa010/stoa0255.stoa010.perseus-lat2.xml
In Seneca De ira 2, remove all hyphens and combine separated word parts, including those separated by a pb element (move the second part to the prior page). Perform Latin spellcheck, correct typos. Some uncertain (older and variant) spellings remain.
=> Combine hyphenated word-halves (also over pb elements). Spellcheck

data/phi0474/phi056/phi0474.phi056.perseus-lat1.xml
This is a possible Latin form (so it would pass any spellcheck), but wrong in the context; I compared it with several editions on the internet.
=> Correct typo dent > deerit in phi0474.phi056.perseus-lat1.xml

data/phi0972/phi001f/phi0972.phi001f.perseus-lat1.xml
The edition of Petronius's fragments (see name of branch) was missing closing head tags, which I added. It is still not valid TEI XML because of the lemma elements and id attributes in pb. Now it is valid XML, however.
=> Correct markup (add missing closing tags for head elements)

data/stoa0045/stoa002/stoa0045.stoa002.perseus-lat2.xml
It was causing an error when extracting the text. It should remain broken until we figure out what is going on.
=> Introducted error into stoa0045.stoa002

data/phi1017/phi013/phi1017.phi013.perseus-lat2.xml
As I was retrieving some extract, I saw that hyphenation was still in this file. Just removed it using following rules in this exact order applied only on `//p` in Oxygen: 
| Pattern | Replacement |
| --------- | ----------------- |
| `(\w+)\-\s+(\w+)` | `$1$2` |  
| `(\w+)\-\s*(\<pb\s+xml:id="p.\d+"\s*\/\>)\s*(\w+)` | `$1$3$2` |
=> (1017.013.lat2) Remove hyphenation

data/phi0972/__cts__.xml, data/phi0972/phi001/__cts__.xml, data/phi0972/phi001/phi0972.phi001.perseus-lat2.xml, data/phi0972/phi001/phi0972.phi001.perseus-lat2b.xml
, marked as lat2b as it is not a "fair" conversion :
- `<quote/>` moved to “”
- `<p />` moved to `<lb unit="paragraph" />`
- `<milestone />` moved to `<div><ab /></div>`
- `<l />` are now always in `<lg />`
This at least is an answer to the fact this text is gonna be complex to keep with all its informations.
=> (0972.001) Proposed a forked version of lat1

data/phi0914/__cts__.xml, data/phi0914/phi001/__cts__.xml
Three students converted old files sent to me by @balmas a while ago to reconstruct a real version of Livy's work ( https://github.com/Chartes-TNAH/tite-live ). This was the original files sent to me https://github.com/Chartes-TNAH/tite-live/tree/25fb2c3a5a44409ca70060db24279ea2e4f6d313/sources
I would recommend to actually remove all other Livy's files as well and put back the other sources for these, as URNs are messed up and lat1 somewhere does not connect to lat1 somewhere else.
=> (phi0914.phi001.lat2) Added Capitains transformation 

data/phi1002/__cts__.xml
not sure if there was a good reason for the brackets ?
=> remove brackets

data/phi0448/phi001/__cts__.xml, data/phi0448/phi002/__cts__.xml, data/phi0474/phi002/phi0474.phi002.perseus-lat2.xml, data/phi0474/phi007/phi0474.phi007.perseus-lat2.xml, data/phi0474/phi015/phi0474.phi015.perseus-lat2.xml, data/phi0474/phi016/phi0474.phi016.perseus-lat2.xml, data/phi0474/phi019/phi0474.phi019.perseus-lat2.xml, data/phi0893/phi001/__cts__.xml, data/phi0972/phi001/__cts__.xml, data/stoa0276/__cts__.xml
1. remove erroneous reference to Seneca in Petronius metadata
2. Corrected author name for stoa0276 to Pseudo-Tertullian
3. Fixed cts title metadata for Caesar's Gallic War and Civil War
4. Converted betacode to unicode in some of Cicero's texts
=> minor cts and betacode fixes

data/phi0472/phi001/phi0472.phi001.perseus-eng3.xml, data/phi0472/phi001/phi0472.phi001.perseus-eng4.xml, data/phi0472/phi001/phi0472.phi001.perseus-lat2.xml
Updated headers to reflect First1K standards.
Also @lcerrato I have a question for you. The two headers for the English translations that are from the same edition have two different ways of showing responsibility in the monogr section. 
phi0472.phi001.perseus-eng3 has:
<respStmt>
<name>Sir Richard Francis Burton</name>
<resp>translator</resp>
</respStmt>
while phi0472.phi001.perseus-eng4 has:
<editor role="editor">Leonard C. Smithers</editor>    
I wasn't sure what one should be used. Thanks!
=> phi0472.phi001

data/phi1038/__cts__.xml, data/phi1038/phi001/__cts__.xml, data/phi1038/phi001/phi1038.phi001.perseus-lat1.xml
Renamed main CTS file-text group incorrectly listed as Julius Paris instead of Valerius Maximus
Updated CTS metadata for edition.
Updated header information.
URN has not yet been bumped but file is showing up in Scaife Viewer.
=> phi1038.phi001.perseus-lat1

data/phi0690/phi001/__cts__.xml, data/phi0690/phi001/phi0690.phi001.perseus-eng2.xml, data/phi0690/phi001/phi0690.phi001.perseus-lat2.xml, data/phi0690/phi002/__cts__.xml, data/phi0690/phi002/phi0690.phi002.perseus-eng2.xml, data/phi0690/phi002/phi0690.phi002.perseus-lat2.xml, data/phi0690/phi003/__cts__.xml, data/phi0690/phi003/phi0690.phi003.perseus-eng2.xml, data/phi0690/phi003/phi0690.phi003.perseus-lat2.xml
Corrected _cts.xml for phi0690.phi003.perseus-eng2 also updated the file header to current standards.
Updated headers for both phi0690.phi003.perseus-lat2 and perseus-eng2
Fix #430 
Per issue #431.
=> (phi0690)-phi0690.phi001-phi0690.phi003.perseus-eng2/lat2_cts.xml

data/phi0959/phi001/__cts__.xml, data/phi0959/phi001/phi0959.phi001.perseus-eng2.xml, data/phi0959/phi001/phi0959.phi001.perseus-lat2.xml, data/phi0959/phi002/__cts__.xml, data/phi0959/phi002/phi0959.phi002.perseus-eng2.xml, data/phi0959/phi002/phi0959.phi002.perseus-lat2.xml, data/phi0959/phi003/__cts__.xml, data/phi0959/phi003/phi0959.phi003.perseus-eng2.xml, data/phi0959/phi003/phi0959.phi003.perseus-lat2.xml, data/phi0959/phi004/__cts__.xml, data/phi0959/phi004/phi0959.phi004.perseus-eng2.xml, data/phi0959/phi004/phi0959.phi004.perseus-lat2.xml
My first efforts at updating Perseus headers for Ovid, and I have already hit several questions for you @lcerrato 
1) Ovid is the name for the textggroup, but I have left the Latin name`<author xml:lang="lat">P. Ovidius Naso</author>`for the author name in these first two files as you recommended using M. Tullius Cicero for Cicero in the headers and bibliographic descriptions for his workis.
2) In phi0959.phi001.perseus-eng2 I found `<respStmt>
<name>Anne Mahoney</name>
<resp>edited for Perseus</resp>
</respStmt>`
within the `<monogr>`section. I'm pretty sure this is incorrect, because shouldn't this section just have bibliographic information regarding the original publication. There is actually no editor for this 1855 publication, or none named. Shouldn't this editor statement regarding …
=> (phi0959)_phi0959.phi001._phi0959.phi004.perseus-eng2/lat2

data/phi0134/__cts__.xml, data/phi0134/phi001/__cts__.xml, data/phi0134/phi001/phi0134.phi001.perseus-eng2.xml, data/phi0134/phi001/phi0134.phi001.perseus-lat2.xml, data/phi0134/phi002/__cts__.xml, data/phi0134/phi002/phi0134.phi002.perseus-eng2.xml, data/phi0134/phi002/phi0134.phi002.perseus-lat2.xml, data/phi0134/phi003/__cts__.xml, data/phi0134/phi003/phi0134.phi003.perseus-eng2.xml, data/phi0134/phi003/phi0134.phi003.perseus-lat2.xml, data/phi0134/phi004/__cts__.xml, data/phi0134/phi004/phi0134.phi004.perseus-eng2.xml, data/phi0134/phi004/phi0134.phi004.perseus-lat2.xml, data/phi0134/phi005/__cts__.xml, data/phi0134/phi005/phi0134.phi005.perseus-eng2.xml, data/phi0134/phi005/phi0134.phi005.perseus-lat2.xml, data/phi0134/phi006/__cts__.xml, data/phi0134/phi006/phi0134.phi006.perseus-eng2.xml, data/phi0134/phi006/phi0134.phi006.perseus-lat2.xml
Deleted Latin name from textgroup with up to date practice, but left the
full Latin name for author in header and bibl descriptions.
Updated cts_.xml files
Updated the bibls and added in page links to online files.
=> (phi0134)_all files

data/phi0478/__cts__.xml, data/phi0478/phi003/__cts__.xml, data/phi0478/phi003/phi0478.phi003.perseus-lat2.xml
Updated cts_.xml
Added in a structured bibl for phi0478.phi003.opp-lat2
@lcerrato  I added in a fill bibliographic description according to the cts metadata. Is that ok?
Previously it had simply said:
`<p>Follows the 1902 OCT</p>`
=> (phi0478)phi0478.phi003

data/phi2331/__cts__.xml, data/phi2331/phi001/__cts__.xml, data/phi2331/phi001/phi2331.phi001.perseus-lat2.xml
This is an initial pull request to start updating the files for the Scriptores Historiae Augustae.
The textgroup for this group was in error, it was one of the attributed author names so I changed it from
`   <ti:groupname xml:lang="lat">Vopiscus, Flavius</ti:groupname>` to
<ti:groupname xml:lang="lat">Scriptores Historiae Augustae</ti:groupname>
I am also making a number of changes to the headers @lcerrato if you approve. 
I'm taking out  Ainsworth O'Brien-Moore as an editor/translator from those work files where he didn't contribute and will do the same for Susan Ballou, only David Magie should be at the individual work header level for all of the files.
I'm also taking out the attributed author names for works such as Capitolinus, Julius, fl. 300, etc. and instead am going to go with …
=> (phi2331)_all_files

data/phi1017/__cts__.xml
Updated textgroup name to eliminate plays as a first step towards merging the two Seneca the Younger textgroups per discussion in Scaife meeting today re issue (https://github.com/scaife-viewer/scaife-viewer/issues/571).
=> (phi1017)_textgroup_name_change

data/stoa0040/stoa0040.stoa011.perseus-eng1.xml
There is an extra `</titleStmt>` closing tag. It makes the XML invalid.
=> remove extra titleStmt (stoa0040.stoa011.perseus-eng1.xml)

.github/workflows/ci.yml, data/phi1014/__cts__.xml, data/phi1014/phi001/__cts__.xml, data/phi1014/phi001/phi1014.phi001.perseus-lat1.xml, data/phi1014/phi002/__cts__.xml, data/phi1014/phi002/phi1014.phi002.perseus-lat1.xml, data/phi1014/phi003/__cts__.xml, data/phi1014/phi003/phi1014.phi003.perseus-lat1.xml, data/phi1014/phi004/__cts__.xml, data/phi1014/phi004/phi1014.phi004.perseus-lat1.xml
I updated the metadata, headers and CTS for all these files. They are currently appearing in Scaife but the URNs have not been bumped.
@lcerrato these files do appear to be correctly CTSized if I am not missing anything, were they just not bumped?
=> (phi1014)_all_files

data/stoa0255/stoa004/__cts__.xml, data/stoa0255/stoa004/stoa0255.stoa004.perseus-lat2.xml
Re #593 
Updated cts_xml and metadata for first Seneca file.
Also want to see if build passes with two files.
=> stoa0255.stoa004_first_pass

data/phi1017/phi011/phi1017.phi011.perseus-lat2.xml
Fixed some final sigmas (σ/ς) and restored quite a few missing Greek words from the source edition on archive.org (https://archive.org/details/petronius00petruoft/page/378/mode/2up).
=> phi1017.phi011.perseus-lat2.xml Restore missing greek/ocr errors
